name: Compile LaTeX with pdflatex

on:
  push:
    paths:
      - "**.tex"
      - "**.bib"
      - ".github/workflows/pdflatex.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v2

      - name: Compile LaTeX document
        run: |
          sudo apt-get update && sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-science texlive-bibtex-extra
          pdflatex main.tex
          bibtex main
          pdflatex main.tex
          pdflatex main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdf
          path: main.pdf
